Using TensorFlow backend.
Traceback (most recent call last):
  File "discriminatorfeatureextractor.py", line 58, in <module>
    model4=load_model('discriminator_only_model.h5')
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/models.py", line 240, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/models.py", line 301, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/layers/__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/models.py", line 1199, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/layers/__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/utils/generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/engine/topology.py", line 1210, in from_config
    return cls(**config)
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/layers/core.py", line 481, in __init__
    super(Flatten, self).__init__(**kwargs)
  File "/home/apps/PYTHONPACKAGES/2.7.13/ucs4/gnu/447/KERAS/2.0.3/gnu/lib/python2.7/site-packages/Keras-2.0.3-py2.7.egg/keras/engine/topology.py", line 281, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', u'data_format')
